/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiError } from './apiError';

/**
 * Creates an instance of InvalidRequest
 */
interface InvalidRequest {
  /** An error message pertaining to what the issue could be */
  result?: string;
}

export class InvalidRequestError extends ApiError<InvalidRequest> {}
