/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiError } from './apiError';

/**
 * Creates an instance of UnauthorizedRequestError
 */
interface UnauthorizedRequestError {
  /** The message containing the reason behind the request being unauthorized */
  message?: string;
}

export class UnauthorizedRequestErrorError extends ApiError<UnauthorizedRequestError> {}
