apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: node-mfa-location
  description: Links to additional entities in the node-mfa repository.
  annotations:
    github.com/project-slug: Bandwidth/node-mfa
spec:
  targets:
    - ./component.yaml
