/**
 * TwoFactorAuthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const APIException = require('./APIException');

/**
 * Creates an instance of InvalidRequestException
 */
class InvalidRequestException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * An error message pertaining to what the issue could be
         */
        this.result = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'result', realName: 'result' },
        ]);
    }
}

module.exports = InvalidRequestException;
