/**
 * TwoFactorAuthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of TwoFactorVerifyRequestSchema
 */
class TwoFactorVerifyRequestSchema extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.to = this.constructor.getValue(obj.to);
        this.from = this.constructor.getValue(obj.from);
        this.applicationId = this.constructor.getValue(obj.applicationId);
        this.scope = this.constructor.getValue(obj.scope);
        this.digits = this.constructor.getValue(obj.digits);
        this.expirationTimeInMinutes = this.constructor.getValue(obj.expirationTimeInMinutes);
        this.code = this.constructor.getValue(obj.code);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'to', realName: 'to' },
            { name: 'from', realName: 'from' },
            { name: 'applicationId', realName: 'applicationId' },
            { name: 'scope', realName: 'scope' },
            { name: 'digits', realName: 'digits' },
            { name: 'expirationTimeInMinutes', realName: 'expirationTimeInMinutes' },
            { name: 'code', realName: 'code' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = TwoFactorVerifyRequestSchema;
