/**
 * TwoFactorAuthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const TwoFactorCodeRequestSchema = require('../lib/Models/TwoFactorCodeRequestSchema');
const TwoFactorVoiceResponse = require('../lib/Models/TwoFactorVoiceResponse');
const TwoFactorMessagingResponse = require('../lib/Models/TwoFactorMessagingResponse');
const TwoFactorVerifyRequestSchema = require('../lib/Models/TwoFactorVerifyRequestSchema');
const TwoFactorVerifyCodeResponse = require('../lib/Models/TwoFactorVerifyCodeResponse');
const InvalidRequestException = require('../lib/Exceptions/InvalidRequestException');

const classMap = {
    TwoFactorCodeRequestSchema,
    TwoFactorVoiceResponse,
    TwoFactorMessagingResponse,
    TwoFactorVerifyRequestSchema,
    TwoFactorVerifyCodeResponse,
    InvalidRequestException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
