/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TwoFactorVerifyRequestSchema {
  /** The phone number to send the 2fa code to. */
  to: string;
  /** The application unique ID, obtained from Bandwidth. */
  applicationId: string;
  /** An optional field to denote what scope or action the 2fa code is addressing.  If not supplied, defaults to "2FA". */
  scope?: string;
  /** The time period, in minutes, to validate the 2fa code.  By setting this to 3 minutes, it will mean any code generated within the last 3 minutes are still valid.  The valid range for expiration time is between 0 and 15 minutes, exclusively and inclusively, respectively. */
  expirationTimeInMinutes: number;
  /** The generated 2fa code to check if valid */
  code: string;
}

export const twoFactorVerifyRequestSchemaSchema: Schema<TwoFactorVerifyRequestSchema> = object(
  {
    to: ['to', string()],
    applicationId: ['applicationId', string()],
    scope: ['scope', optional(string())],
    expirationTimeInMinutes: ['expirationTimeInMinutes', number()],
    code: ['code', string()],
  }
);
