/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TwoFactorMessagingResponse {
  messageId?: string;
}

export const twoFactorMessagingResponseSchema: Schema<TwoFactorMessagingResponse> = object(
  { messageId: ['messageId', optional(string())] }
);
