/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TwoFactorCodeRequestSchema {
  /** The phone number to send the 2fa code to. */
  to: string;
  /** The application phone number, the sender of the 2fa code. */
  from: string;
  /** The application unique ID, obtained from Bandwidth. */
  applicationId: string;
  /** An optional field to denote what scope or action the 2fa code is addressing.  If not supplied, defaults to "2FA". */
  scope?: string;
  /** The message format of the 2fa code.  There are three values that the system will replace "{CODE}", "{NAME}", "{SCOPE}".  The "{SCOPE}" and "{NAME} value template are optional, while "{CODE}" must be supplied.  As the name would suggest, code will be replace with the actual 2fa code.  Name is replaced with the application name, configured during provisioning of 2fa.  The scope value is the same value sent during the call and partitioned by the server. */
  message: string;
  /** The number of digits for your 2fa code.  The valid number ranges from 2 to 8, inclusively. */
  digits: number;
}

export const twoFactorCodeRequestSchemaSchema: Schema<TwoFactorCodeRequestSchema> = object(
  {
    to: ['to', string()],
    from: ['from', string()],
    applicationId: ['applicationId', string()],
    scope: ['scope', optional(string())],
    message: ['message', string()],
    digits: ['digits', number()],
  }
);
