/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TwoFactorVoiceResponse {
  callId?: string;
}

export const twoFactorVoiceResponseSchema: Schema<TwoFactorVoiceResponse> = object(
  { callId: ['callId', optional(string())] }
);
