/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface TwoFactorVerifyCodeResponse {
  valid?: boolean;
}

export const twoFactorVerifyCodeResponseSchema: Schema<TwoFactorVerifyCodeResponse> = object(
  { valid: ['valid', optional(boolean())] }
);
