name: Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build --if-present
    - name: npm test
      run: npm run test --if-present --passWithNoTests
