name: Deploy
on:
  release:
    types:
      - published
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Build and test npm package
      run: |
           npm install
           npm run test --if-present
      env:
        BANDWIDTH_ACCOUNT_ID: ${{ secrets.BANDWIDTH_ACCOUNT_ID }}
        BANDWIDTH_USERNAME: ${{ secrets.BANDWIDTH_USERNAME }}
        BANDWIDTH_PASSWORD: ${{ secrets.BANDWIDTH_PASSWORD }}
        MFA_VOICE_APPLICATION_ID: ${{ secrets.MFA_VOICE_APPLICATION_ID }}
        MFA_MESSAGING_APPLICATION_ID: ${{ secrets.MFA_MESSAGING_APPLICATION_ID }}
        PHONE_NUMBER_INBOUND: ${{ secrets.PHONE_NUMBER_INBOUND }}
        PHONE_NUMBER_MFA: ${{ secrets.PHONE_NUMBER_MFA }}
    - name: Publish npm package
      run: |
            npm version $RELEASE_VERSION --no-git-tag-version
            npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
