name: Validate SDK

on:
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    name: Validate SDK 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: NPM Install
      run: npm install
    - name: NPM Build
      run: npm run build --if-present
    - name: NPM Test
      run: npm run test --if-present
      env:
        BANDWIDTH_ACCOUNT_ID: ${{ secrets.BANDWIDTH_ACCOUNT_ID }}
        BANDWIDTH_USERNAME: ${{ secrets.BANDWIDTH_USERNAME }}
        BANDWIDTH_PASSWORD: ${{ secrets.BANDWIDTH_PASSWORD }}
        MFA_VOICE_APPLICATION_ID: ${{ secrets.MFA_VOICE_APPLICATION_ID }}
        MFA_MESSAGING_APPLICATION_ID: ${{ secrets.MFA_MESSAGING_APPLICATION_ID }}
        PHONE_NUMBER_INBOUND: ${{ secrets.PHONE_NUMBER_INBOUND }}
        PHONE_NUMBER_MFA: ${{ secrets.PHONE_NUMBER_MFA }}
